#ifndef AT_COMMANDS_H_
#define AT_COMMANDS_H_

#define ENTER_COMMAND_MODE_STRING "+++"
#define COMMAND_MODE_ACK "OK\r"
#define EXIT_COMMAND_MODE "CN"

#define SERIAL_ADDRESS_HIGH "SH"
#define SERIAL_ADDRESS_LOW "SL"

#define MAXIMUM_PACKET_PAYLOAD_BYTES "NP"
#define TOGGLE_API_MODE "AP"

#endif